CREATE TABLE IF NOT EXISTS "LOTE_PAGO_MASIVO" (
    "ID_LOTE" UUID PRIMARY KEY,
    "ID_CORRELACION" UUID NOT NULL,
    "RUC_EMPRESA" VARCHAR(20) NOT NULL,
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40) NOT NULL,
    "TIPO_SERVICIO" VARCHAR(20) NOT NULL,
    "NOMBRE_ARCHIVO" VARCHAR(255) NOT NULL,
    "HASH_ARCHIVO" VARCHAR(128) NOT NULL,
    "CANAL" VARCHAR(20) NOT NULL,
    "RECIBIDO_POR" VARCHAR(100),
    "TOTAL_REGISTROS" INTEGER NOT NULL,
    "MONTO_CONTROL" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "ESTADO" VARCHAR(40) NOT NULL,
    "MOTIVO_RECHAZO" VARCHAR(500),
    "FECHA_RECEPCION" TIMESTAMPTZ NOT NULL,
    "FECHA_VALIDACION" TIMESTAMPTZ,
    "FECHA_FONDEO" TIMESTAMPTZ,
    "ID_FONDEO_CORE" VARCHAR(80),
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "FECHA_CONTABLE" DATE,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_LOTE_ESTADO" ON "LOTE_PAGO_MASIVO" ("ESTADO");
CREATE INDEX IF NOT EXISTS "IDX_LOTE_HASH_ARCHIVO" ON "LOTE_PAGO_MASIVO" ("NOMBRE_ARCHIVO", "HASH_ARCHIVO", "FECHA_RECEPCION");

CREATE TABLE IF NOT EXISTS "ARCHIVO_CARGADO" (
    "ID_ARCHIVO_CARGADO" UUID PRIMARY KEY,
    "ID_LOTE" UUID NOT NULL,
    "NOMBRE_ARCHIVO_ORIGINAL" VARCHAR(255) NOT NULL,
    "NOMBRE_ARCHIVO_SANITIZADO" VARCHAR(255) NOT NULL,
    "EXTENSION_ARCHIVO" VARCHAR(10) NOT NULL,
    "HASH_ARCHIVO" VARCHAR(128) NOT NULL,
    "TIPO_CONTENIDO" VARCHAR(100),
    "TAMANO_ARCHIVO_BYTES" BIGINT NOT NULL,
    "REFERENCIA_ALMACENAMIENTO" VARCHAR(500),
    "FECHA_CARGA" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "FK_ARCHIVO_CARGADO_LOTE" FOREIGN KEY ("ID_LOTE") REFERENCES "LOTE_PAGO_MASIVO"("ID_LOTE")
);

CREATE INDEX IF NOT EXISTS "IDX_ARCHIVO_CARGADO_LOTE" ON "ARCHIVO_CARGADO" ("ID_LOTE");

CREATE TABLE IF NOT EXISTS "ERROR_VALIDACION_LOTE" (
    "ID_ERROR_VALIDACION" UUID PRIMARY KEY,
    "ID_LOTE" UUID NOT NULL,
    "CODIGO" VARCHAR(80) NOT NULL,
    "NOMBRE_CAMPO" VARCHAR(100),
    "MENSAJE" VARCHAR(500) NOT NULL,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "FK_ERROR_VALIDACION_LOTE" FOREIGN KEY ("ID_LOTE") REFERENCES "LOTE_PAGO_MASIVO"("ID_LOTE")
);

CREATE INDEX IF NOT EXISTS "IDX_ERROR_VALIDACION_LOTE" ON "ERROR_VALIDACION_LOTE" ("ID_LOTE");

CREATE TABLE IF NOT EXISTS "SOLICITUD_FONDEO_LOTE" (
    "ID_SOLICITUD_FONDEO" UUID PRIMARY KEY,
    "ID_LOTE" UUID NOT NULL,
    "CLAVE_IDEMPOTENCIA" VARCHAR(120) NOT NULL,
    "ESTADO_SOLICITUD" VARCHAR(40) NOT NULL,
    "MONTO_SOLICITADO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "ID_FONDEO_CORE" VARCHAR(80),
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "FECHA_CONTABLE" DATE,
    "ESTADO_RESPUESTA_CORE" VARCHAR(40),
    "MENSAJE_RESPUESTA_CORE" VARCHAR(500),
    "FECHA_SOLICITUD" TIMESTAMPTZ NOT NULL,
    "FECHA_RESPUESTA" TIMESTAMPTZ,
    CONSTRAINT "FK_SOLICITUD_FONDEO_LOTE" FOREIGN KEY ("ID_LOTE") REFERENCES "LOTE_PAGO_MASIVO"("ID_LOTE"),
    CONSTRAINT "UK_SOLICITUD_FONDEO_IDEMPOTENCIA" UNIQUE ("CLAVE_IDEMPOTENCIA")
);

CREATE INDEX IF NOT EXISTS "IDX_SOLICITUD_FONDEO_LOTE" ON "SOLICITUD_FONDEO_LOTE" ("ID_LOTE");

CREATE TABLE IF NOT EXISTS "LINEA_PAGO_LOTE" (
    "ID_LINEA" UUID PRIMARY KEY,
    "ID_LOTE" UUID NOT NULL,
    "NUMERO_SECUENCIA" INTEGER NOT NULL,
    "IDENTIFICACION_BENEFICIARIO" VARCHAR(30) NOT NULL,
    "NOMBRE_BENEFICIARIO" VARCHAR(120) NOT NULL,
    "NUMERO_CUENTA_DESTINO" VARCHAR(40) NOT NULL,
    "CODIGO_ENRUTAMIENTO" VARCHAR(10) NOT NULL,
    "MONTO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "REFERENCIA" VARCHAR(200),
    "EMAIL_NOTIFICACION" VARCHAR(120),
    "ESTADO" VARCHAR(40) NOT NULL,
    "ID_EVENTO" UUID,
    "FECHA_PUBLICACION" TIMESTAMPTZ,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL,
    CONSTRAINT "FK_LINEA_PAGO_LOTE" FOREIGN KEY ("ID_LOTE") REFERENCES "LOTE_PAGO_MASIVO"("ID_LOTE"),
    CONSTRAINT "UK_LINEA_PAGO_SECUENCIA" UNIQUE ("ID_LOTE", "NUMERO_SECUENCIA")
);

CREATE INDEX IF NOT EXISTS "IDX_LINEA_PAGO_LOTE" ON "LINEA_PAGO_LOTE" ("ID_LOTE");
CREATE INDEX IF NOT EXISTS "IDX_LINEA_PAGO_ESTADO" ON "LINEA_PAGO_LOTE" ("ESTADO");
